export interface Country {
  name: string
  iso2: string
  dialCode: string
  flag: string
}

export const COUNTRIES: Country[] = [
  { name: "United States", iso2: "US", dialCode: "+1", flag: "\ud83c\uddfa\ud83c\uddf8" },
  { name: "Canada", iso2: "CA", dialCode: "+1", flag: "\ud83c\udde8\ud83c\udde6" },
  { name: "United Kingdom", iso2: "GB", dialCode: "+44", flag: "\ud83c\uddec\ud83c\udde7" },
  { name: "Egypt", iso2: "EG", dialCode: "+20", flag: "\ud83c\uddea\ud83c\uddec" },
  { name: "Saudi Arabia", iso2: "SA", dialCode: "+966", flag: "\ud83c\uddf8\ud83c\udde6" },
  { name: "United Arab Emirates", iso2: "AE", dialCode: "+971", flag: "\ud83c\udde6\ud83c\uddea" },
  { name: "India", iso2: "IN", dialCode: "+91", flag: "\ud83c\uddee\ud83c\uddf3" },
  { name: "China", iso2: "CN", dialCode: "+86", flag: "\ud83c\udde8\ud83c\uddf3" },
  { name: "Germany", iso2: "DE", dialCode: "+49", flag: "\ud83c\udde9\ud83c\uddea" },
  { name: "France", iso2: "FR", dialCode: "+33", flag: "\ud83c\uddeb\ud83c\uddf7" },
  { name: "Spain", iso2: "ES", dialCode: "+34", flag: "\ud83c\uddea\ud83c\uddf8" },
  { name: "Italy", iso2: "IT", dialCode: "+39", flag: "\ud83c\uddee\ud83c\uddf9" },
  { name: "Turkey", iso2: "TR", dialCode: "+90", flag: "\ud83c\uddf9\ud83c\uddf7" },
  { name: "Brazil", iso2: "BR", dialCode: "+55", flag: "\ud83c\udde7\ud83c\uddf7" },
  { name: "Mexico", iso2: "MX", dialCode: "+52", flag: "\ud83c\uddf2\ud83c\uddfd" },
  { name: "Australia", iso2: "AU", dialCode: "+61", flag: "\ud83c\udde6\ud83c\uddfa" },
  { name: "Japan", iso2: "JP", dialCode: "+81", flag: "\ud83c\uddef\ud83c\uddf5" },
  { name: "South Korea", iso2: "KR", dialCode: "+82", flag: "\ud83c\uddf0\ud83c\uddf7" },
  { name: "Indonesia", iso2: "ID", dialCode: "+62", flag: "\ud83c\uddee\ud83c\udde9" },
  { name: "Thailand", iso2: "TH", dialCode: "+66", flag: "\ud83c\uddf9\ud83c\udded" },
  { name: "Malaysia", iso2: "MY", dialCode: "+60", flag: "\ud83c\uddf2\ud83c\uddfe" },
  { name: "Singapore", iso2: "SG", dialCode: "+65", flag: "\ud83c\uddf8\ud83c\uddec" },
  { name: "Philippines", iso2: "PH", dialCode: "+63", flag: "\ud83c\uddf5\ud83c\udded" },
  { name: "Vietnam", iso2: "VN", dialCode: "+84", flag: "\ud83c\uddfb\ud83c\uddf3" },
  { name: "Pakistan", iso2: "PK", dialCode: "+92", flag: "\ud83c\uddf5\ud83c\uddf0" },
  { name: "Bangladesh", iso2: "BD", dialCode: "+880", flag: "\ud83c\udde7\ud83c\udde9" },
  { name: "Nigeria", iso2: "NG", dialCode: "+234", flag: "\ud83c\uddf3\ud83c\uddec" },
  { name: "South Africa", iso2: "ZA", dialCode: "+27", flag: "\ud83c\uddff\ud83c\udde6" },
  { name: "Kenya", iso2: "KE", dialCode: "+254", flag: "\ud83c\uddf0\ud83c\uddea" },
  { name: "Ethiopia", iso2: "ET", dialCode: "+251", flag: "\ud83c\uddea\ud83c\uddf9" },
  { name: "Ghana", iso2: "GH", dialCode: "+233", flag: "\ud83c\uddec\ud83c\udded" },
  { name: "Morocco", iso2: "MA", dialCode: "+212", flag: "\ud83c\uddf2\ud83c\udde6" },
  { name: "Algeria", iso2: "DZ", dialCode: "+213", flag: "\ud83c\udde9\ud83c\uddff" },
  { name: "Tunisia", iso2: "TN", dialCode: "+216", flag: "\ud83c\uddf9\ud83c\uddf3" },
  { name: "Libya", iso2: "LY", dialCode: "+218", flag: "\ud83c\uddf1\ud83c\uddfe" },
  { name: "Sudan", iso2: "SD", dialCode: "+249", flag: "\ud83c\uddf8\ud83c\udde9" },
  { name: "Iraq", iso2: "IQ", dialCode: "+964", flag: "\ud83c\uddee\ud83c\uddf6" },
  { name: "Jordan", iso2: "JO", dialCode: "+962", flag: "\ud83c\uddef\ud83c\uddf4" },
  { name: "Lebanon", iso2: "LB", dialCode: "+961", flag: "\ud83c\uddf1\ud83c\udde7" },
  { name: "Kuwait", iso2: "KW", dialCode: "+965", flag: "\ud83c\uddf0\ud83c\uddfc" },
  { name: "Qatar", iso2: "QA", dialCode: "+974", flag: "\ud83c\uddf6\ud83c\udde6" },
  { name: "Bahrain", iso2: "BH", dialCode: "+973", flag: "\ud83c\udde7\ud83c\udded" },
  { name: "Oman", iso2: "OM", dialCode: "+968", flag: "\ud83c\uddf4\ud83c\uddf2" },
  { name: "Yemen", iso2: "YE", dialCode: "+967", flag: "\ud83c\uddfe\ud83c\uddea" },
  { name: "Syria", iso2: "SY", dialCode: "+963", flag: "\ud83c\uddf8\ud83c\uddfe" },
  { name: "Palestine", iso2: "PS", dialCode: "+970", flag: "\ud83c\uddf5\ud83c\uddf8" },
  { name: "Russia", iso2: "RU", dialCode: "+7", flag: "\ud83c\uddf7\ud83c\uddfa" },
  { name: "Ukraine", iso2: "UA", dialCode: "+380", flag: "\ud83c\uddfa\ud83c\udde6" },
  { name: "Poland", iso2: "PL", dialCode: "+48", flag: "\ud83c\uddf5\ud83c\uddf1" },
  { name: "Netherlands", iso2: "NL", dialCode: "+31", flag: "\ud83c\uddf3\ud83c\uddf1" },
  { name: "Belgium", iso2: "BE", dialCode: "+32", flag: "\ud83c\udde7\ud83c\uddea" },
  { name: "Austria", iso2: "AT", dialCode: "+43", flag: "\ud83c\udde6\ud83c\uddf9" },
  { name: "Switzerland", iso2: "CH", dialCode: "+41", flag: "\ud83c\udde8\ud83c\udded" },
  { name: "Sweden", iso2: "SE", dialCode: "+46", flag: "\ud83c\uddf8\ud83c\uddea" },
  { name: "Norway", iso2: "NO", dialCode: "+47", flag: "\ud83c\uddf3\ud83c\uddf4" },
  { name: "Denmark", iso2: "DK", dialCode: "+45", flag: "\ud83c\udde9\ud83c\uddf0" },
  { name: "Finland", iso2: "FI", dialCode: "+358", flag: "\ud83c\uddeb\ud83c\uddee" },
  { name: "Ireland", iso2: "IE", dialCode: "+353", flag: "\ud83c\uddee\ud83c\uddea" },
  { name: "Portugal", iso2: "PT", dialCode: "+351", flag: "\ud83c\uddf5\ud83c\uddf9" },
  { name: "Greece", iso2: "GR", dialCode: "+30", flag: "\ud83c\uddec\ud83c\uddf7" },
  { name: "Czech Republic", iso2: "CZ", dialCode: "+420", flag: "\ud83c\udde8\ud83c\uddff" },
  { name: "Romania", iso2: "RO", dialCode: "+40", flag: "\ud83c\uddf7\ud83c\uddf4" },
  { name: "Hungary", iso2: "HU", dialCode: "+36", flag: "\ud83c\udded\ud83c\uddfa" },
  { name: "Argentina", iso2: "AR", dialCode: "+54", flag: "\ud83c\udde6\ud83c\uddf7" },
  { name: "Colombia", iso2: "CO", dialCode: "+57", flag: "\ud83c\udde8\ud83c\uddf4" },
  { name: "Chile", iso2: "CL", dialCode: "+56", flag: "\ud83c\udde8\ud83c\uddf1" },
  { name: "Peru", iso2: "PE", dialCode: "+51", flag: "\ud83c\uddf5\ud83c\uddea" },
  { name: "Venezuela", iso2: "VE", dialCode: "+58", flag: "\ud83c\uddfb\ud83c\uddea" },
  { name: "Ecuador", iso2: "EC", dialCode: "+593", flag: "\ud83c\uddea\ud83c\udde8" },
  { name: "Dominican Republic", iso2: "DO", dialCode: "+1", flag: "\ud83c\udde9\ud83c\uddf4" },
  { name: "New Zealand", iso2: "NZ", dialCode: "+64", flag: "\ud83c\uddf3\ud83c\uddff" },
  { name: "Israel", iso2: "IL", dialCode: "+972", flag: "\ud83c\uddee\ud83c\uddf1" },
  { name: "Afghanistan", iso2: "AF", dialCode: "+93", flag: "\ud83c\udde6\ud83c\uddeb" },
  { name: "Iran", iso2: "IR", dialCode: "+98", flag: "\ud83c\uddee\ud83c\uddf7" },
  { name: "Nepal", iso2: "NP", dialCode: "+977", flag: "\ud83c\uddf3\ud83c\uddf5" },
  { name: "Sri Lanka", iso2: "LK", dialCode: "+94", flag: "\ud83c\uddf1\ud83c\uddf0" },
  { name: "Myanmar", iso2: "MM", dialCode: "+95", flag: "\ud83c\uddf2\ud83c\uddf2" },
  { name: "Cambodia", iso2: "KH", dialCode: "+855", flag: "\ud83c\uddf0\ud83c\udded" },
  { name: "Laos", iso2: "LA", dialCode: "+856", flag: "\ud83c\uddf1\ud83c\udde6" },
  { name: "Mongolia", iso2: "MN", dialCode: "+976", flag: "\ud83c\uddf2\ud83c\uddf3" },
  { name: "Kazakhstan", iso2: "KZ", dialCode: "+7", flag: "\ud83c\uddf0\ud83c\uddff" },
  { name: "Uzbekistan", iso2: "UZ", dialCode: "+998", flag: "\ud83c\uddfa\ud83c\uddff" },
  { name: "Azerbaijan", iso2: "AZ", dialCode: "+994", flag: "\ud83c\udde6\ud83c\uddff" },
  { name: "Georgia", iso2: "GE", dialCode: "+995", flag: "\ud83c\uddec\ud83c\uddea" },
  { name: "Armenia", iso2: "AM", dialCode: "+374", flag: "\ud83c\udde6\ud83c\uddf2" },
  { name: "Belarus", iso2: "BY", dialCode: "+375", flag: "\ud83c\udde7\ud83c\uddfe" },
  { name: "Tanzania", iso2: "TZ", dialCode: "+255", flag: "\ud83c\uddf9\ud83c\uddff" },
  { name: "Uganda", iso2: "UG", dialCode: "+256", flag: "\ud83c\uddfa\ud83c\uddec" },
  { name: "Cameroon", iso2: "CM", dialCode: "+237", flag: "\ud83c\udde8\ud83c\uddf2" },
  { name: "Ivory Coast", iso2: "CI", dialCode: "+225", flag: "\ud83c\udde8\ud83c\uddee" },
  { name: "Senegal", iso2: "SN", dialCode: "+221", flag: "\ud83c\uddf8\ud83c\uddf3" },
  { name: "Zimbabwe", iso2: "ZW", dialCode: "+263", flag: "\ud83c\uddff\ud83c\uddfc" },
  { name: "Zambia", iso2: "ZM", dialCode: "+260", flag: "\ud83c\uddff\ud83c\uddf2" },
  { name: "Mozambique", iso2: "MZ", dialCode: "+258", flag: "\ud83c\uddf2\ud83c\uddff" },
  { name: "Madagascar", iso2: "MG", dialCode: "+261", flag: "\ud83c\uddf2\ud83c\uddec" },
  { name: "Guatemala", iso2: "GT", dialCode: "+502", flag: "\ud83c\uddec\ud83c\uddf9" },
  { name: "Cuba", iso2: "CU", dialCode: "+53", flag: "\ud83c\udde8\ud83c\uddfa" },
  { name: "Honduras", iso2: "HN", dialCode: "+504", flag: "\ud83c\udded\ud83c\uddf3" },
  { name: "Bolivia", iso2: "BO", dialCode: "+591", flag: "\ud83c\udde7\ud83c\uddf4" },
  { name: "Paraguay", iso2: "PY", dialCode: "+595", flag: "\ud83c\uddf5\ud83c\uddfe" },
  { name: "Uruguay", iso2: "UY", dialCode: "+598", flag: "\ud83c\uddfa\ud83c\uddfe" },
  { name: "Costa Rica", iso2: "CR", dialCode: "+506", flag: "\ud83c\udde8\ud83c\uddf7" },
  { name: "Panama", iso2: "PA", dialCode: "+507", flag: "\ud83c\uddf5\ud83c\udde6" },
  { name: "El Salvador", iso2: "SV", dialCode: "+503", flag: "\ud83c\uddf8\ud83c\uddfb" },
  { name: "Nicaragua", iso2: "NI", dialCode: "+505", flag: "\ud83c\uddf3\ud83c\uddee" },
  { name: "Jamaica", iso2: "JM", dialCode: "+1", flag: "\ud83c\uddef\ud83c\uddf2" },
  { name: "Trinidad and Tobago", iso2: "TT", dialCode: "+1", flag: "\ud83c\uddf9\ud83c\uddf9" },
  { name: "Haiti", iso2: "HT", dialCode: "+509", flag: "\ud83c\udded\ud83c\uddf9" },
  { name: "Iceland", iso2: "IS", dialCode: "+354", flag: "\ud83c\uddee\ud83c\uddf8" },
  { name: "Luxembourg", iso2: "LU", dialCode: "+352", flag: "\ud83c\uddf1\ud83c\uddfa" },
  { name: "Malta", iso2: "MT", dialCode: "+356", flag: "\ud83c\uddf2\ud83c\uddf9" },
  { name: "Cyprus", iso2: "CY", dialCode: "+357", flag: "\ud83c\udde8\ud83c\uddfe" },
  { name: "Estonia", iso2: "EE", dialCode: "+372", flag: "\ud83c\uddea\ud83c\uddea" },
  { name: "Latvia", iso2: "LV", dialCode: "+371", flag: "\ud83c\uddf1\ud83c\uddfb" },
  { name: "Lithuania", iso2: "LT", dialCode: "+370", flag: "\ud83c\uddf1\ud83c\uddf9" },
  { name: "Slovakia", iso2: "SK", dialCode: "+421", flag: "\ud83c\uddf8\ud83c\uddf0" },
  { name: "Slovenia", iso2: "SI", dialCode: "+386", flag: "\ud83c\uddf8\ud83c\uddee" },
  { name: "Croatia", iso2: "HR", dialCode: "+385", flag: "\ud83c\udded\ud83c\uddf7" },
  { name: "Serbia", iso2: "RS", dialCode: "+381", flag: "\ud83c\uddf7\ud83c\uddf8" },
  { name: "Bosnia and Herzegovina", iso2: "BA", dialCode: "+387", flag: "\ud83c\udde7\ud83c\udde6" },
  { name: "Albania", iso2: "AL", dialCode: "+355", flag: "\ud83c\udde6\ud83c\uddf1" },
  { name: "North Macedonia", iso2: "MK", dialCode: "+389", flag: "\ud83c\uddf2\ud83c\uddf0" },
  { name: "Bulgaria", iso2: "BG", dialCode: "+359", flag: "\ud83c\udde7\ud83c\uddec" },
  { name: "Moldova", iso2: "MD", dialCode: "+373", flag: "\ud83c\uddf2\ud83c\udde9" },
  { name: "Kosovo", iso2: "XK", dialCode: "+383", flag: "\ud83c\uddfd\ud83c\uddf0" },
  { name: "Kyrgyzstan", iso2: "KG", dialCode: "+996", flag: "\ud83c\uddf0\ud83c\uddec" },
  { name: "Tajikistan", iso2: "TJ", dialCode: "+992", flag: "\ud83c\uddf9\ud83c\uddef" },
  { name: "Turkmenistan", iso2: "TM", dialCode: "+993", flag: "\ud83c\uddf9\ud83c\uddf2" },
  { name: "Mauritania", iso2: "MR", dialCode: "+222", flag: "\ud83c\uddf2\ud83c\uddf7" },
  { name: "Mali", iso2: "ML", dialCode: "+223", flag: "\ud83c\uddf2\ud83c\uddf1" },
  { name: "Guinea", iso2: "GN", dialCode: "+224", flag: "\ud83c\uddec\ud83c\uddf3" },
  { name: "Burkina Faso", iso2: "BF", dialCode: "+226", flag: "\ud83c\udde7\ud83c\uddeb" },
  { name: "Niger", iso2: "NE", dialCode: "+227", flag: "\ud83c\uddf3\ud83c\uddea" },
  { name: "Chad", iso2: "TD", dialCode: "+235", flag: "\ud83c\uddf9\ud83c\udde9" },
  { name: "Togo", iso2: "TG", dialCode: "+228", flag: "\ud83c\uddf9\ud83c\uddec" },
  { name: "Benin", iso2: "BJ", dialCode: "+229", flag: "\ud83c\udde7\ud83c\uddef" },
  { name: "Sierra Leone", iso2: "SL", dialCode: "+232", flag: "\ud83c\uddf8\ud83c\uddf1" },
  { name: "Liberia", iso2: "LR", dialCode: "+231", flag: "\ud83c\uddf1\ud83c\uddf7" },
  { name: "Gambia", iso2: "GM", dialCode: "+220", flag: "\ud83c\uddec\ud83c\uddf2" },
  { name: "Guinea-Bissau", iso2: "GW", dialCode: "+245", flag: "\ud83c\uddec\ud83c\uddfc" },
  { name: "Cape Verde", iso2: "CV", dialCode: "+238", flag: "\ud83c\udde8\ud83c\uddfb" },
  { name: "Gabon", iso2: "GA", dialCode: "+241", flag: "\ud83c\uddec\ud83c\udde6" },
  { name: "Congo", iso2: "CG", dialCode: "+242", flag: "\ud83c\udde8\ud83c\uddec" },
  { name: "DR Congo", iso2: "CD", dialCode: "+243", flag: "\ud83c\udde8\ud83c\udde9" },
  { name: "Angola", iso2: "AO", dialCode: "+244", flag: "\ud83c\udde6\ud83c\uddf4" },
  { name: "Rwanda", iso2: "RW", dialCode: "+250", flag: "\ud83c\uddf7\ud83c\uddfc" },
  { name: "Burundi", iso2: "BI", dialCode: "+257", flag: "\ud83c\udde7\ud83c\uddee" },
  { name: "Somalia", iso2: "SO", dialCode: "+252", flag: "\ud83c\uddf8\ud83c\uddf4" },
  { name: "Djibouti", iso2: "DJ", dialCode: "+253", flag: "\ud83c\udde9\ud83c\uddef" },
  { name: "Eritrea", iso2: "ER", dialCode: "+291", flag: "\ud83c\uddea\ud83c\uddf7" },
  { name: "Namibia", iso2: "NA", dialCode: "+264", flag: "\ud83c\uddf3\ud83c\udde6" },
  { name: "Botswana", iso2: "BW", dialCode: "+267", flag: "\ud83c\udde7\ud83c\uddfc" },
  { name: "Lesotho", iso2: "LS", dialCode: "+266", flag: "\ud83c\uddf1\ud83c\uddf8" },
  { name: "Eswatini", iso2: "SZ", dialCode: "+268", flag: "\ud83c\uddf8\ud83c\uddff" },
  { name: "Malawi", iso2: "MW", dialCode: "+265", flag: "\ud83c\uddf2\ud83c\uddfc" },
  { name: "Comoros", iso2: "KM", dialCode: "+269", flag: "\ud83c\uddf0\ud83c\uddf2" },
  { name: "Seychelles", iso2: "SC", dialCode: "+248", flag: "\ud83c\uddf8\ud83c\udde8" },
  { name: "Mauritius", iso2: "MU", dialCode: "+230", flag: "\ud83c\uddf2\ud83c\uddfa" },
  { name: "South Sudan", iso2: "SS", dialCode: "+211", flag: "\ud83c\uddf8\ud83c\uddf8" },
  { name: "Central African Republic", iso2: "CF", dialCode: "+236", flag: "\ud83c\udde8\ud83c\uddeb" },
  { name: "Equatorial Guinea", iso2: "GQ", dialCode: "+240", flag: "\ud83c\uddec\ud83c\uddf6" },
  { name: "Sao Tome and Principe", iso2: "ST", dialCode: "+239", flag: "\ud83c\uddf8\ud83c\uddf9" },
  { name: "Bhutan", iso2: "BT", dialCode: "+975", flag: "\ud83c\udde7\ud83c\uddf9" },
  { name: "Maldives", iso2: "MV", dialCode: "+960", flag: "\ud83c\uddf2\ud83c\uddfb" },
  { name: "Brunei", iso2: "BN", dialCode: "+673", flag: "\ud83c\udde7\ud83c\uddf3" },
  { name: "Timor-Leste", iso2: "TL", dialCode: "+670", flag: "\ud83c\uddf9\ud83c\uddf1" },
  { name: "Papua New Guinea", iso2: "PG", dialCode: "+675", flag: "\ud83c\uddf5\ud83c\uddec" },
  { name: "Fiji", iso2: "FJ", dialCode: "+679", flag: "\ud83c\uddeb\ud83c\uddef" },
  { name: "Solomon Islands", iso2: "SB", dialCode: "+677", flag: "\ud83c\uddf8\ud83c\udde7" },
  { name: "Vanuatu", iso2: "VU", dialCode: "+678", flag: "\ud83c\uddfb\ud83c\uddfa" },
  { name: "Samoa", iso2: "WS", dialCode: "+685", flag: "\ud83c\uddfc\ud83c\uddf8" },
  { name: "Tonga", iso2: "TO", dialCode: "+676", flag: "\ud83c\uddf9\ud83c\uddf4" },
  { name: "Kiribati", iso2: "KI", dialCode: "+686", flag: "\ud83c\uddf0\ud83c\uddee" },
  { name: "Palau", iso2: "PW", dialCode: "+680", flag: "\ud83c\uddf5\ud83c\uddfc" },
  { name: "Micronesia", iso2: "FM", dialCode: "+691", flag: "\ud83c\uddeb\ud83c\uddf2" },
  { name: "Marshall Islands", iso2: "MH", dialCode: "+692", flag: "\ud83c\uddf2\ud83c\udded" },
  { name: "Nauru", iso2: "NR", dialCode: "+674", flag: "\ud83c\uddf3\ud83c\uddf7" },
  { name: "Tuvalu", iso2: "TV", dialCode: "+688", flag: "\ud83c\uddf9\ud83c\uddfb" },
  { name: "Andorra", iso2: "AD", dialCode: "+376", flag: "\ud83c\udde6\ud83c\udde9" },
  { name: "Monaco", iso2: "MC", dialCode: "+377", flag: "\ud83c\uddf2\ud83c\udde8" },
  { name: "San Marino", iso2: "SM", dialCode: "+378", flag: "\ud83c\uddf8\ud83c\uddf2" },
  { name: "Vatican City", iso2: "VA", dialCode: "+379", flag: "\ud83c\uddfb\ud83c\udde6" },
  { name: "Liechtenstein", iso2: "LI", dialCode: "+423", flag: "\ud83c\uddf1\ud83c\uddee" },
  { name: "Belize", iso2: "BZ", dialCode: "+501", flag: "\ud83c\udde7\ud83c\uddff" },
  { name: "Bahamas", iso2: "BS", dialCode: "+1", flag: "\ud83c\udde7\ud83c\uddf8" },
  { name: "Barbados", iso2: "BB", dialCode: "+1", flag: "\ud83c\udde7\ud83c\udde7" },
  { name: "Saint Lucia", iso2: "LC", dialCode: "+1", flag: "\ud83c\uddf1\ud83c\udde8" },
  { name: "Grenada", iso2: "GD", dialCode: "+1", flag: "\ud83c\uddec\ud83c\udde9" },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", dialCode: "+1", flag: "\ud83c\uddfb\ud83c\udde8" },
  { name: "Antigua and Barbuda", iso2: "AG", dialCode: "+1", flag: "\ud83c\udde6\ud83c\uddec" },
  { name: "Dominica", iso2: "DM", dialCode: "+1", flag: "\ud83c\udde9\ud83c\uddf2" },
  { name: "Guyana", iso2: "GY", dialCode: "+592", flag: "\ud83c\uddec\ud83c\uddfe" },
  { name: "Suriname", iso2: "SR", dialCode: "+597", flag: "\ud83c\uddf8\ud83c\uddf7" },
  { name: "French Guiana", iso2: "GF", dialCode: "+594", flag: "\ud83c\uddec\ud83c\uddeb" },
  { name: "Greenland", iso2: "GL", dialCode: "+299", flag: "\ud83c\uddec\ud83c\uddf1" },
  { name: "Faroe Islands", iso2: "FO", dialCode: "+298", flag: "\ud83c\uddeb\ud83c\uddf4" },
  { name: "Gibraltar", iso2: "GI", dialCode: "+350", flag: "\ud83c\uddec\ud83c\uddee" },
  { name: "Jersey", iso2: "JE", dialCode: "+44", flag: "\ud83c\uddef\ud83c\uddea" },
  { name: "Guernsey", iso2: "GG", dialCode: "+44", flag: "\ud83c\uddec\ud83c\uddec" },
  { name: "Isle of Man", iso2: "IM", dialCode: "+44", flag: "\ud83c\uddee\ud83c\uddf2" },
  { name: "Puerto Rico", iso2: "PR", dialCode: "+1", flag: "\ud83c\uddf5\ud83c\uddf7" },
  { name: "US Virgin Islands", iso2: "VI", dialCode: "+1", flag: "\ud83c\uddfb\ud83c\uddee" },
  { name: "Guam", iso2: "GU", dialCode: "+1", flag: "\ud83c\uddec\ud83c\uddfa" },
  { name: "American Samoa", iso2: "AS", dialCode: "+1", flag: "\ud83c\udde6\ud83c\uddf8" },
  { name: "Northern Mariana Islands", iso2: "MP", dialCode: "+1", flag: "\ud83c\uddf2\ud83c\uddf5" },
  { name: "Cayman Islands", iso2: "KY", dialCode: "+1", flag: "\ud83c\uddf0\ud83c\uddfe" },
  { name: "Bermuda", iso2: "BM", dialCode: "+1", flag: "\ud83c\udde7\ud83c\uddf2" },
  { name: "Aruba", iso2: "AW", dialCode: "+297", flag: "\ud83c\udde6\ud83c\uddfc" },
  { name: "Curacao", iso2: "CW", dialCode: "+599", flag: "\ud83c\udde8\ud83c\uddfc" },
  { name: "Sint Maarten", iso2: "SX", dialCode: "+1", flag: "\ud83c\uddf8\ud83c\uddfd" },
  { name: "Hong Kong", iso2: "HK", dialCode: "+852", flag: "\ud83c\udded\ud83c\uddf0" },
  { name: "Macau", iso2: "MO", dialCode: "+853", flag: "\ud83c\uddf2\ud83c\uddf4" },
  { name: "Taiwan", iso2: "TW", dialCode: "+886", flag: "\ud83c\uddf9\ud83c\uddfc" },
  { name: "North Korea", iso2: "KP", dialCode: "+850", flag: "\ud83c\uddf0\ud83c\uddf5" },
].sort((a, b) => a.name.localeCompare(b.name))
