'use client'
import { useState } from 'react'
import Link from 'next/link'

export default function Login(){const [mode,setMode]=useState<'login'|'signup'>('login');const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
  const handleSubmit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError(null);setLoading(true);
    // Supabase client integration is the next incremental step: supabase.auth.signInWithPassword() /
    // supabase.auth.signUp() will replace this block once the client and env vars are configured.
    setTimeout(()=>{setLoading(false);setError('Authentication is coming next: the Supabase client is being wired into this form.');},400);};
 return <main className="min-h-screen grid place-items-center px-5 py-20"><div className="w-full max-w-md"><Link href="/" className="font-display text-xl font-extrabold tracking-[.18em]">DROP<span className="text-[#d8b45a]">VERSE</span></Link><div className="card mt-8 rounded-3xl p-7"><p className="text-sm text-[#d8b45a]">{mode==='login'?'Welcome back':'Start your journey'}</p><h1 className="font-display mt-2 text-3xl font-extrabold">{mode==='login'?'Sign in to DropVerse':'Create your account'}</h1><p className="mt-3 text-sm leading-6 text-[#8fa29c]">Access services, work samples and the tools you need to build your Drop Servicing business.</p><form onSubmit={handleSubmit} className="mt-7 space-y-4"><input name="email" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3.5 outline-none focus:border-[#d8b45a]/50" type="email" placeholder="Email address" required/><input name="password" className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3.5 outline-none focus:border-[#d8b45a]/50" type="password" placeholder="Password" required minLength={8}/>{error&&<p className="rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-2.5 text-sm text-red-200">{error}</p>}<button disabled={loading} className="w-full rounded-xl bg-[#d8b45a] px-5 py-3.5 font-bold text-[#10221f] transition disabled:opacity-60">{loading?'Processing...':mode==='login'?'Sign In':'Create Account'}</button></form><button type="button" onClick={()=>setMode(mode==='login'?'signup':'login')} className="mt-5 w-full text-sm text-[#9aaca6]">{mode==='login'?"Don't have an account? Sign up":"Already have an account? Sign in"}</button></div></div></main>}
